

- Bookmarks:

    - Cloudflare:
        - abbr:
          icon: cloudflare.png
          href: https://dash.cloudflare.com
          description: Domains

    - Change Detection:
        - abbr:
          icon: changedetection.png
          href: https://change.hughboi.cc
          description: Merch Tracking
    
    - Git:
        - abbr:
          icon: github-light.png
          href: https://github.com
          description: Public Git

    - IT Tools:
        - abbr:
          icon: it-tools-light.png
          href: https://it-tools.tech/encryption
          description: Lots of tools

    - Jelly Fin:
        - abbr:
          icon: jellyfin.png
          href: http://corntube.net:8096
          description: Aaron Server

    - Paste Bin:
        - abbr:
          icon: pastebin.png
          href: https://pastebin.com
          description: Public File Share


    - Tailscale:
        - abbr:
          icon: headscale.png
          href: https://login.tailscale.com/admin/machines
          description: Mesh VPN



  

    - Reddit:
        - abbr:
          icon: reddit.png
          href: https://reddit.com
          description: Feed
