services:
  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/home/node/.n8n
      - ./files:/files
    depends_on:
      - postgres
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entrypoints=http"
      - "traefik.http.routers.n8n.rule=Host(`n8n.hughboi.cc`)"
      - "traefik.http.middlewares.n8n-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.n8n.middlewares=n8n-https-redirect"
      - "traefik.http.routers.n8n-secure.entrypoints=https"
      - "traefik.http.routers.n8n-secure.rule=Host(`n8n.hughboi.cc`)"
      - "traefik.http.routers.n8n-secure.tls=true"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - n8n

  # If you're running your own external PostgreSQL instance, you can comment out this service
  postgres:
    container_name: n8n-db
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - n8n


# volumes:
#   db:
  

networks:
  n8n:
  proxy:
    external: true
