---
auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093 #change this to Prometheus Alertmanager name or IP http://promalerts:9093


limits_config:
  ingestion_rate_mb: 20          # Set ingestion rate to 20MB/s (Adjust as needed)
  ingestion_rate_strategy: "global" # Strategy to apply rate limits (global, user, or tenant)
  max_entries_limit_per_query: 5000  # Adjust if queries are too large
  max_query_length: 7d            # Maximum time range for queries
