services:
  adguardhome:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: loki
      options:
        loki-url: https://loki.hughboi.cc/loki/api/v1/push
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: non-blocking
    volumes:
      - ./adguard-data/work:/opt/adguardhome/work
      - ./adguard-data/conf:/opt/adguardhome/conf
    environment:
      TZ: America/Denver
      ADGUARD_DNS_: 192.168.100.10#5335 # specify the IP of the docker container on the unbound network. Specified below under ipv4_address
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.entrypoints=http
      - traefik.http.routers.adguard.rule=Host(`adguard.hughboi.cc`)
      - traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.adguard.middlewares=adguard-https-redirect
      - traefik.http.routers.adguard-secure.entrypoints=https
      - traefik.http.routers.adguard-secure.rule=Host(`adguard.hughboi.cc`)
      - traefik.http.routers.adguard-secure.tls=true
      - traefik.http.routers.adguard-secure.service=adguard
      - traefik.http.services.adguard.loadbalancer.server.port=80
      - traefik.docker.network=proxy
      - diun.enable=true
    ports:
      - 53:53/tcp
      - 53:53/udp
      # - 853:853/tcp # DNS over TLS - Unbound can do this
      # - 784:784/udp
      # - 3000:3000/tcp # Setup webui
      # - 80:80/tcp # Web port
      # - 449:443/tcp # Web port secure
    networks:
      unbound:
        ipv4_address: 192.168.100.9
      proxy: null



  unbound:
    container_name: unbound
    image: mvance/unbound:1.22.0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: loki
      options:
        loki-url: https://loki.hughboi.cc/loki/api/v1/push
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: non-blocking
    volumes:
      - ./unbound/:/opt/unbound/etc/unbound
    healthcheck:
      test:
        - CMD
        - dig
        - "@127.0.0.1"
        - -p
        - "53"
        - cloudflare.com
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 5335:53/tcp
      - 5335:53/udp
    networks:
      unbound:
        ipv4_address: 192.168.100.10


  
networks:
  unbound:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/27
  proxy:
    external: true
