services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    command:
      - serve
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"

    volumes:
      - cache:/var/cache/ntfy
      - ./etc/ntfy:/etc/ntfy
    environment:
      - TZ=America/Denver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.entrypoints=http"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.hughboi.cc`)"
      - "traefik.http.middlewares.ntfy-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.ntfy.middlewares=ntfy-https-redirect"
      - "traefik.http.routers.ntfy-secure.entrypoints=https"
      - "traefik.http.routers.ntfy-secure.rule=Host(`ntfy.hughboi.cc`)"
      - "traefik.http.routers.ntfy-secure.tls=true"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      

volumes:
  cache:

networks:
  proxy:
    external: true



