
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    volumes:
      - ./config:/app/config
     # - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_VAR_PROXMOX_USERNAME=$HOMEPAGE_VAR_PROXMOX_USERNAME
      - HOMEPAGE_VAR_PROXMOX_PASSWORD=$HOMEPAGE_VAR_PROXMOX_PASSWORD
      - HOMEPAGE_VAR_TRUENAS_KEY=$HOMEPAGE_VAR_TRUENAS_KEY
      - HOMEPAGE_VAR_ADGUARD_USERNAME=$HOMEPAGE_VAR_ADGUARD_USERNAME
      - HOMEPAGE_VAR_ADGUARD_PASSWORD=$HOMEPAGE_VAR_ADGUARD_PASSWORD
      - HOMEPAGE_VAR_UNIFI_USERNAME=$HOMEPAGE_VAR_UNIFI_USERNAME
      - HOMEPAGE_VAR_UNIFI_PASSWORD=$HOMEPAGE_VAR_UNIFI_PASSWORD
      - HOMEPAGE_VAR_IMMICH_KEY=$HOMEPAGE_VAR_IMMICH_KEY
      - HOMEPAGE_VAR_GITEA_KEY=$HOMEPAGE_VAR_GITEA_KEY
      - HOMEPAGE_VAR_PBS_USERNAME=$HOMEPAGE_VAR_PBS_USERNAME
      - HOMEPAGE_VAR_PBS_PASSWORD=$HOMEPAGE_VAR_PBS_PASSWORD
      - HOMEPAGE_VAR_GRAFANA_USERNAME=$HOMEPAGE_VAR_GRAFANA_USERNAME
      - HOMEPAGE_VAR_GRAFANA_PASSWPRD=$HOMEPAGE_VAR_GRAFANA_PASSWORD
      - HOMEPAGE_VAR_PORTAINER_KEY=$HOMEPAGE_VAR_PORTAINER_KEY
      - HOMEPAGE_VAR_TAILSCALE_KEY=$HOMEPAGE_VAR_TAILSCALE_KEY
      - HOMEPAGE_VAR_AUTHENTIK_KEY=$HOMEPAGE_VAR_AUTHENTIK_KEY
      - HOMEPAGE_ALLOWED_HOSTS=$HOMEPAGE_ALLOWED_HOSTS # needed since 3/17/25
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home.entrypoints=http"
      - "traefik.http.routers.home.rule=Host(`home.hughboi.cc`)"
      - "traefik.http.middlewares.home-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.home.middlewares=home-https-redirect"
      - "traefik.http.routers.home-secure.entrypoints=https"
      - "traefik.http.routers.home-secure.rule=Host(`home.hughboi.cc`)"
      - "traefik.http.routers.home-secure.tls=true"
      - "traefik.http.routers.home-secure.service=home"
      - "traefik.http.services.home.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - homepage

networks:
  proxy:
    external: true 
  homepage:
    external: true
