services:
  mealie:
    container_name: mealie    
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - data:/app/data/
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.entrypoints=http"
      - "traefik.http.routers.mealie.rule=Host(`mealie.hughboi.cc`)"
      - "traefik.http.middlewares.mealie-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mealie.middlewares=mealie-https-redirect"
      - "traefik.http.routers.mealie-secure.entrypoints=https"
      - "traefik.http.routers.mealie-secure.rule=Host(`mealie.hughboi.cc`)"
      - "traefik.http.routers.mealie-secure.tls=true"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy


volumes:
  data:


networks:
  proxy:
    external: true

