services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - homeassistant-db
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Denver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home-assistant.entrypoints=http"
      - "traefik.http.routers.home-assistant.rule=Host(`home-assistant.hughboi.cc`)"
      - "traefik.http.middlewares.home-assistant-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.home-assistant.middlewares=home-assistant-https-redirect"
      - "traefik.http.routers.home-assistant-secure.entrypoints=https"
      - "traefik.http.routers.home-assistant-secure.rule=Host(`home-assistant.hughboi.cc`)"
      - "traefik.http.routers.home-assistant-secure.tls=true"
      - "traefik.http.routers.home-assistant-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.home-assistant-secure.service=home-assistant"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
      - "traefik.docker.network=proxy"
    networks:
      proxy:
      home-assistant:

  homeassistant-db:
    container_name: homeassistant-db
    image: docker.io/postgres:16.3
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=homeassistant_user
      - POSTGRES_PASSWORD=CHANGEME
      - POSTGRES_DB=homeassistant-db
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    networks:
      home-assistant:
   

volumes:
  db:

networks:
  proxy:
    external: true
  home-assistant:
