# my global config
### GLOBAL PARAMETERS
global:
  scrape_interval: 60s
  evaluation_interval: 60s
  body_size_limit: 100MB
  sample_limit: 2000
  target_limit: 75
  label_limit: 75
  label_name_length_limit: 300
  label_value_length_limit: 300


### ALERTS via Prometheus Alert manager
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
 - /etc/prometheus/alert-rules.yml


### TARGETS TO SCRAPE
scrape_configs:

  - job_name: 'crowdsec'
    static_configs:
      - targets: ['10.10.10.10:6060']
  
  - job_name: 'unifipoller'
    scrape_interval: 30s
    static_configs:
    - targets: ['10.10.10.10:9130']
